<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>SemanticSwamp.Blazor</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\Images\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SemanticSwamp.DAL\SemanticSwamp.DAL.csproj" />
    <ProjectReference Include="..\SemanticSwamp.Shared\SemanticSwamp.Shared.csproj" />
  </ItemGroup>

</Project>
