using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using SemanticSwamp.DAL.EFModels;

namespace SemanticSwamp.DAL.Context;

/// <summary>
/// EF Core DbContext for the SemanticSwamp SQL Server database.
///
/// This context is the single point of access for all SQL Server persistence in the application.
/// It is registered as a scoped service so that each Blazor Server SignalR circuit (i.e. each
/// browser tab) gets its own tracked instance, preventing state from leaking between users.
///
/// The class is declared partial so that EF scaffolding can regenerate the DbSets and
/// OnModelCreating configuration without overwriting hand-written extensions that live in a
/// separate partial file.
///
/// Table overview:
///   Categories           \u2014 classification labels (e.g. "Lecture Notes")
///   Collections          \u2014 top-level groupings (e.g. "Project Alpha")
///   DocumentUploads      \u2014 uploaded files with their Base64 content, summary, and processing state
///   DocumentUploadTerms  \u2014 many-to-many join between uploads and keyword terms
///   IdTrackers           \u2014 single-row counter used to assign monotonic IDs to Qdrant vector points
///   Terms                \u2014 keyword/concept tags applied to document uploads
/// </summary>
public partial class SemanticSwampDBContext : DbContext
{
    public SemanticSwampDBContext(DbContextOptions<SemanticSwampDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Collection> Collections { get; set; }

    public virtual DbSet<DocumentUpload> DocumentUploads { get; set; }

    /// <summary>Join table rows linking document uploads to their term tags.</summary>
    public virtual DbSet<DocumentUploadTerm> DocumentUploadTerms { get; set; }

    /// <summary>Single-row table tracking the last Qdrant vector ID issued.</summary>
    public virtual DbSet<IdTracker> IdTrackers { get; set; }

    public virtual DbSet<Term> Terms { get; set; }

    /// <summary>
    /// Configures column types, max-lengths, default values, and foreign-key constraints
    /// to match the existing database schema. This is generated by EF scaffolding and
    /// should not be edited by hand \u2014 use the partial method OnModelCreatingPartial for
    /// any application-specific fluent configuration.
    /// </summary>
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Category>(entity =>
        {
            entity.Property(e => e.Name)
                .HasMaxLength(2000)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Collection>(entity =>
        {
            entity.Property(e => e.Name)
                .HasMaxLength(2000)
                .IsUnicode(false);
        });

        modelBuilder.Entity<DocumentUpload>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Uploads");

            entity.Property(e => e.Base64Data).IsUnicode(false);
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())", "DF_Uploads_CreatedOn")
                .HasColumnType("datetime");
            entity.Property(e => e.FileName)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_DocumentUploads_IsActive");
            entity.Property(e => e.Summary).IsUnicode(false);

            // ClientSetNull \u2014 deleting a Collection/Category will not cascade-delete its documents;
            // instead EF will set the FK to null (handled at the client side). This prevents
            // accidental bulk-deletes when a collection is removed.
            entity.HasOne(d => d.Category).WithMany(p => p.DocumentUploads)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DocumentUploads_Categories");

            entity.HasOne(d => d.Collection).WithMany(p => p.DocumentUploads)
                .HasForeignKey(d => d.CollectionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DocumentUploads_Collections");
        });

        modelBuilder.Entity<DocumentUploadTerm>(entity =>
        {
            entity.HasOne(d => d.DocumentUpload).WithMany(p => p.DocumentUploadTerms)
                .HasForeignKey(d => d.DocumentUploadId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DocumentUploadTerms_DocumentUploads");

            entity.HasOne(d => d.Term).WithMany(p => p.DocumentUploadTerms)
                .HasForeignKey(d => d.TermId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DocumentUploadTerms_Terms");
        });

        modelBuilder.Entity<IdTracker>(entity =>
        {
            entity.ToTable("IdTracker");
        });

        modelBuilder.Entity<Term>(entity =>
        {
            entity.Property(e => e.Name)
                .HasMaxLength(2000)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    /// <summary>
    /// Extension point for hand-written fluent configuration. Implement this in a separate
    /// partial class file to avoid being overwritten when EF scaffolding regenerates this file.
    /// </summary>
    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
