using System;
using System.Collections.Generic;

namespace SemanticSwamp.DAL.EFModels;

/// <summary>
/// Represents a document category — a secondary classification within a Collection
/// (e.g. "Lecture Notes", "Reference", "Research Papers").
///
/// While Collections are coarse-grained groupings, Categories allow finer sub-grouping
/// within a Collection. Each DocumentUpload belongs to exactly one Category.
/// </summary>
public partial class Category
{
    /// <summary>Primary key. Auto-generated by the database.</summary>
    public int Id { get; set; }

    /// <summary>Human-readable category name shown in dropdowns and the documents table.</summary>
    public string Name { get; set; } = null!;

    /// <summary>Navigation property — all document uploads that belong to this category.</summary>
    public virtual ICollection<DocumentUpload> DocumentUploads { get; set; } = new List<DocumentUpload>();
}
