using System;
using System.Collections.Generic;

namespace SemanticSwamp.DAL.EFModels;

/// <summary>
/// Represents a document collection — a high-level grouping used to organise uploaded documents
/// (e.g. "Project Alpha", "Study Notes").
///
/// Collections are the top-level organisational unit. Each DocumentUpload belongs to exactly one
/// Collection. During RAG search, the model first determines which Collection best matches the
/// user's question and then scopes the vector search to that Collection for higher relevance.
/// </summary>
public partial class Collection
{
    /// <summary>Primary key. Auto-generated by the database.</summary>
    public int Id { get; set; }

    /// <summary>Human-readable collection name shown in dropdowns and the documents table.</summary>
    public string Name { get; set; } = null!;

    /// <summary>Navigation property — all document uploads that belong to this collection.</summary>
    public virtual ICollection<DocumentUpload> DocumentUploads { get; set; } = new List<DocumentUpload>();
}
