using System;
using System.Collections.Generic;

namespace SemanticSwamp.DAL.EFModels;

/// <summary>
/// Join table that resolves the many-to-many relationship between DocumentUpload and Term.
///
/// A single document can be tagged with many terms, and the same term can be applied to many
/// documents. EF Core does not materialise a join entity by default for simple many-to-many,
/// but this explicit class is used here so the Term IDs can also be stored in each Qdrant
/// vector entry (as a List&lt;int&gt;) for metadata-based search filtering.
/// </summary>
public partial class DocumentUploadTerm
{
    /// <summary>Primary key. Auto-generated by the database.</summary>
    public int Id { get; set; }

    /// <summary>Foreign key to the Term that has been applied to this document.</summary>
    public int TermId { get; set; }

    /// <summary>Foreign key to the DocumentUpload this tag belongs to.</summary>
    public int DocumentUploadId { get; set; }

    /// <summary>Navigation property to the parent document upload.</summary>
    public virtual DocumentUpload DocumentUpload { get; set; } = null!;

    /// <summary>Navigation property to the applied term.</summary>
    public virtual Term Term { get; set; } = null!;
}
