using System;
using System.Collections.Generic;

namespace SemanticSwamp.DAL.EFModels;

/// <summary>
/// Represents a file that has been uploaded by a user through the Upload modal.
///
/// The full file content is stored as a Base64-encoded string in the database so that it can
/// be downloaded later via the /api/download/{id} endpoint without needing a separate file-
/// storage system. For larger-scale deployments this would be replaced with blob storage.
///
/// After a file is saved, the upload pipeline:
///   1. Generates a text summary via the AI (GetTextSummary) and stores it in Summary.
///   2. Chunks the text and vectorises each chunk into Qdrant (RAGManager.UploadToRAG).
///   3. Sets HasBeenProcessed = true once vectorisation completes.
/// </summary>
public partial class DocumentUpload
{
    /// <summary>Primary key. Auto-generated by the database.</summary>
    public int Id { get; set; }

    /// <summary>Original file name as provided by the user (e.g. "lecture-notes.pdf").</summary>
    public string FileName { get; set; } = null!;

    /// <summary>UTC timestamp of when the record was created. Defaulted by the database to GETDATE().</summary>
    public DateTime CreatedOn { get; set; }

    /// <summary>
    /// The complete file contents encoded as Base64. Stored inline so the file can be
    /// downloaded without a separate storage service. Null if the record was created without
    /// a file (edge case — should not normally occur).
    /// </summary>
    public string? Base64Data { get; set; }

    /// <summary>
    /// Whether this document is currently active/visible. Soft-delete flag — inactive
    /// documents are excluded from normal queries but are not physically removed.
    /// Defaults to true on insert.
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// True once the document has been chunked, embedded, and upserted into Qdrant.
    /// Set to true by RAGManager.UploadToRAG at the end of the processing pipeline.
    /// </summary>
    public bool HasBeenProcessed { get; set; }

    /// <summary>
    /// AI-generated plain-text summary of the file content, produced by UploadManager.GetTextSummary
    /// using the Prompts.SummarizeText prompt. Shown in the expandable row of the documents table.
    /// </summary>
    public string? Summary { get; set; }

    /// <summary>Foreign key to the Collection this document belongs to.</summary>
    public int CollectionId { get; set; }

    /// <summary>Foreign key to the Category this document belongs to.</summary>
    public int CategoryId { get; set; }

    /// <summary>Navigation property to the parent category.</summary>
    public virtual Category Category { get; set; } = null!;

    /// <summary>Navigation property to the parent collection.</summary>
    public virtual Collection Collection { get; set; } = null!;

    /// <summary>Navigation property — the term tags applied to this document.</summary>
    public virtual ICollection<DocumentUploadTerm> DocumentUploadTerms { get; set; } = new List<DocumentUploadTerm>();
}
