using System;
using System.Collections.Generic;

namespace SemanticSwamp.DAL.EFModels;

/// <summary>
/// Represents a keyword or concept tag that can be applied to one or more document uploads
/// (e.g. "machine learning", "neural networks", "RAG").
///
/// Terms allow cross-document tagging so that related documents can be found regardless of
/// which Collection or Category they belong to. The many-to-many relationship between
/// DocumentUpload and Term is resolved through the DocumentUploadTerm join table.
/// Term IDs are also stored in the Qdrant vector entries so they can be used as metadata
/// filters during semantic search.
/// </summary>
public partial class Term
{
    /// <summary>Primary key. Auto-generated by the database.</summary>
    public int Id { get; set; }

    /// <summary>The keyword or concept label, displayed as a pill badge in the upload modal.</summary>
    public string Name { get; set; } = null!;

    /// <summary>Navigation property — join records linking this term to its associated document uploads.</summary>
    public virtual ICollection<DocumentUploadTerm> DocumentUploadTerms { get; set; } = new List<DocumentUploadTerm>();
}
