USE [master]
GO

/****** Object:  Database [SemanticSwamp]    Script Date: 12/30/2025 1:59:30 PM ******/
CREATE DATABASE [SemanticSwamp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SemanticSwamp', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\SemanticSwamp.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SemanticSwamp_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\SemanticSwamp_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SemanticSwamp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SemanticSwamp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SemanticSwamp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SemanticSwamp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SemanticSwamp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SemanticSwamp] SET ARITHABORT OFF 
GO

ALTER DATABASE [SemanticSwamp] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SemanticSwamp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SemanticSwamp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SemanticSwamp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SemanticSwamp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SemanticSwamp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SemanticSwamp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SemanticSwamp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SemanticSwamp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SemanticSwamp] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SemanticSwamp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SemanticSwamp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SemanticSwamp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SemanticSwamp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SemanticSwamp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SemanticSwamp] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SemanticSwamp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SemanticSwamp] SET RECOVERY FULL 
GO

ALTER DATABASE [SemanticSwamp] SET  MULTI_USER 
GO

ALTER DATABASE [SemanticSwamp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SemanticSwamp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SemanticSwamp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SemanticSwamp] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SemanticSwamp] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SemanticSwamp] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SemanticSwamp] SET OPTIMIZED_LOCKING = OFF 
GO

ALTER DATABASE [SemanticSwamp] SET QUERY_STORE = ON
GO

ALTER DATABASE [SemanticSwamp] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [SemanticSwamp] SET  READ_WRITE 
GO


